// This file contains the abbreviations data directly embedded as a JavaScript object
// This avoids the need for fetch requests which can cause MIME type issues

const abbreviationsData = {
    "AI": "Artificial Intelligence",
    "IC": "International Consultant",
    "IPSA": [
        "International Professional Service Agreement",
        "https://popp.undp.org/document/international-personnel-services-agreement"
    ],
    "API": "Application Programming Interface",
    "AFDB": "African Development Bank",
    "AFDF": "African Development Fund",
    "ADR": "Assessment of Development Results",
    "BPPS": "Bureau for Policy and Programme Support",
    "CB": "Crisis Bureau",
    "CLE": "Center for Leadership and Entrepreneurship",
    "COP29": "29th Conference of the Parties",
    "CRP": "Crisis Risk Portfolio",
    "DEM": "Digital Elevation Model",
    "DHS": "Demographic and Health Surveys",
    "DSVI": "Digital Social Vulnerability Index",
    "DRR": "Disaster Risk Reduction",
    "DTM": "Digital Terrain Model",
    "DSM": "Digital Surface Model",
    "EBRD": "European Bank for Reconstruction and Development",
    "EO": "Earth Observation",
    "EU JRC": "European Union Joint Research Centre",
    "FAO": "Food and Agriculture Organization",
    "FTL": "Frontier Tech Leaders",
    "GDP": "Gross Domestic Product",
    "GEE": "Google Earth Engine",
    "ACA": "Argentinean Association of Cooperatives",
    "ADB": "Asian Development Bank",
    "AMMC": "Moroccan Capital Market Association",
    "ASEAN": "Association of Southeast Asian Nations",
    "BYMA": "Argentine Stock Exchange",
    "CEAMSE": "Ecological Coordination Society of the State Metropolitan Area",
    "CEV": "Landfill and Recovery Centres",
    "CMF": "Financial Market Council",
    "EU": "European Union",
    "GG-NAP": "Green Growth National Action Plan",
    "GHG": "Greenhouse Gas",
    "ICMA": "International Capital Market Association",
    "IFC": "International Finance Corporation",
    "ICPSD": "Istanbul International Centre for Private Sector in Development",
    "INDC": "Intended Nationally Determined Contributions",
    "ISDB": "Islamic Development Bank",
    "ISTAC": "Istanbul Environment Management Industry and Trade Company",
    "ISWM": "Integrated Solid Waste Management",
    "JICA": "Japan International Cooperation Agency",
    "JP": "Joint Programme",
    "KPKT": "Ministry of Housing and Local Government",
    "MBT": "Mechanical Biological Treatment",
    "ME": "Municipal Enterprise",
    "MOE": "Municipally Owned Enterprise",
    "MRV": "Measurement, Reporting, and Verification",
    "MSW": "Municipal Solid Waste",
    "MTP": "Medium Term Program",
    "NAP": "National Adaptation Plan",
    "NDC": "Nationally Determined Contribution",
    "NGO": "Non-Governmental Organization",
    "OECD": "Organization for Economic Co-operation and Development",
    "OM": "Operations Management",
    "PPP": "Public-Private Partnership",
    "PS": "Private Sector",
    "RCD": "Recycling of Construction and Demolition Waste",
    "RRR": "Reduce, Reuse, and Recycle",
    "SCEEP": "State Committee of the Republic of Uzbekistan for Ecology and Environmental Protection",
    "SDG": "Sustainable Development Goal",
    "SOE": "State-Owned Enterprise",
    "SRF": "Solid Recovered Fuel",
    "SRI": [
        "Sustainable and Responsible Investment",
        "Socially Responsible Investing"
    ],
    "SSTC": "South-South and Triangular Cooperation",
    "SWM": "Solid Waste Management",
    "TSKB": "Industrial Development Bank of Türkiye",
    "UN": "United Nations",
    "UNDP": "United Nations Development Programme",
    "UNICEF": "United Nations Children's Fund",
    "UNODC": "United Nations Office on Drugs and Crime",
    "UNOSSC": "United Nations Office of South-South Cooperation",
    "WEEE": "Electrical and Electronic Equipment Waste",
    "WHO": "World Health Organization",
    "WTE": "Waste to Energy",
    "GEOTIFF": "Georeferenced Tagged Image File Format",
    "GIS": "Geographic Information System",
    "GNSS": "Global Navigation Satellite System",
    "GPS": "Global Positioning System",
    "HLP": "Housing, Land, and Property",
    "HRSL": "High-Resolution Settlement Layer",
    "IDP": "Internally Displaced Person",
    "ILO": "International Labour Organization",
    "IM": "Information Management",
    "INSAR": "Interferometric Synthetic Aperture Radar",
    "ITM": "Information Technology Management",
    "LDCs": "Least Developed Countries",
    "LIDAR": "Light Detection and Ranging",
    "LULC": "Land Use and Land Cover",
    "MICS": "Multiple Indicator Cluster Surveys",
    "ML": "Machine Learning",
    "MODIS": "Moderate Resolution Imaging Spectroradiometer",
    "NDVI": "Normalized Difference Vegetation Index",
    "NO2": "Nitrogen Dioxide",
    "NRT": "Near Real-Time",
    "NSDI": "National Spatial Data Infrastructure",
    "ODK": "Open Data Kit",
    "OGC": "Open Geospatial Consortium",
    "OSM": "OpenStreetMap",
    "PCA": "Principal Component Analysis",
    "PM2.5": "Particulate Matter 2.5 Microns",
    "POI": "Point of Interest",
    "PSA": "Public Service Announcement",
    "QNEAT3": "QGIS Network Analysis Toolbox 3",
    "REDD+": "Reducing Emissions from Deforestation and Forest Degradation",
    "RS": "Remote Sensing",
    "SAR": "Synthetic Aperture Radar",
    "SCA": "Strategic Cooperation Agreement",
    "SDI": "Spatial Data Infrastructure",
    "SFH": "Sustainable Finance Hub",
    "SHP": "Shapefile",
    "SLUM": "Spatial Livelihoods and Urban Monitoring",
    "SOP": "Standard Operating Procedure",
    "SPOT": "Satellite Pour l'Observation de la Terre",
    "SV": "Social Vulnerability",
    "SVI": "Social Vulnerability Index",
    "TDA": "Transboundary Diagnostic Analysis",
    "UAV": "Unmanned Aerial Vehicle",
    "UNHCR": "United Nations High Commissioner for Refugees",
    "USAID": "U.S. Agency for International Development",
    "WASH": "Water, Sanitation, and Hygiene",
    "WCS": "Web Coverage Service",
    "WFS": "Web Feature Service",
    "WMS": "Web Map Service",
    "WB": "World Bank",
    "XGBoost": "Extreme Gradient Boosting",
    "ZETs": "Zero Emission Trucks",
    "KOICA": "Korea International Cooperation Agency",
    "PVE": "Preventing Violent Extremism",
    "VCA": "Value Chain Analysis",
    "CSOs": "Civil Society Organizations",
    "NCs": "National Consultants",
    "RBAS": "Regional Bureau for Arab States",
    "RBEC": "Regional Bureau for Europe and Central Asia",
    "RSCA": "Regional Service Centre for Africa",
    "CSA": "Conflict Sensitivity Analysis",
    "AfCFTA": "African Continental Free Trade Area",
    "AfDB": "African Development Bank",
    "AU": "African Union",
    "CIS": "Commonwealth of Independent States",
    "ICT": "Information and Communications Technology",
    "IMF": "International Monetary Fund",
    "IP": "Intellectual Property",
    "ITU": "International Telecommunication Union",
    "SDGs": "Sustainable Development Goals",
    "SMEs": "Small and Medium Enterprises",
    "TVET": "Technical and Vocational Education and Training",
    "UNCTAD": "United Nations Conference on Trade and Development",
    "UNESCO": "United Nations Educational, Scientific and Cultural Organization",
    "VC": "Venture Capital",
    "WIPO": "World Intellectual Property Organization",
    "CI/EWS": "Climate Information and Early Warning Systems",
    "NHMS": "National Hydro-Meteorological Services",
    "LDCF": "Least Developed Countries Fund",
    "SCCF": "Special Climate Change Fund",
    "AF": "Adaptation Fund",
    "GCF": "Green Climate Fund",
    "GLOFs": "Glacial Lake Outburst Floods",
    "CIRDA": "Climate Information for Resilient Development in Africa",
    "REAP": "Risk Informed Early Action Partnership",
    "MVI": "Multidimensional Vulnerability Index",
    "SIDS": "Small Island Developing States",
    "PPG": "Public and Publicly Guaranteed Debt",
    "EVI": "Economic and Environmental Vulnerability Index",
    "GNI": "Gross National Income",
    "HAI": "Human Assets Index",
    "CDP": "UN Committee for Development Policy",
    "UNWTO": "United Nations World Tourism Organization",
    "FDI": "Foreign Direct Investment",
    "HDRO": "Human Development Report Office",
    "WDI": "World Development Indicators",
    "UN-OHRLLS": "UN Office of the High Representative for the Least Developed Countries, Landlocked Developing Countries, and Small Island Developing States",
    "SCRALA": "Scaling up Climate Resilient Agriculture and Livelihoods",
    "SAMOA": "Small Island Developing States Accelerated Modalities of Action",
    "AA": "Association Agreement",
    "AR": [
        "Augmented Reality",
        "Autonomous Republic"
    ],
    "ATO": "Anti-Terrorist Operation",
    "AUM": "Assets Under Management",
    "BEPS": "Base Erosion and Profit Shifting",
    "BMO": "Business Membership Organization",
    "BMZ": "Federal Ministry for Economic Cooperation and Development (Germany)",
    "CAGR": "Compound Annual Growth Rate",
    "CBA": "Carbon Border Adjustment",
    "CEA": "Classification of Economic Activities",
    "CEP": "Competitive Economy Program",
    "DCFTA": "Deep and Comprehensive Free Trade Area",
    "DFIs": "Development Finance Institutions",
    "DOBRE": "Decentralization Offering Better Results and Efficiency",
    "EaP": "Eastern Partnership",
    "EBA": "European Business Association",
    "EECA": "Eastern Europe, Russia and Central Asia",
    "EEN": "Enterprise Europe Network",
    "EIB": "European Investment Bank",
    "ERA": "Economic Resilience Activity",
    "ESG": "Environmental, Social, and Governance",
    "FUIB": "First Ukrainian International Bank",
    "FTA": "Free Trade Agreement",
    "GIIN": "Global Impact Investing Network",
    "GIZ": "Deutsche Gesellschaft für Internationale Zusammenarbeit",
    "GSG": "Global Steering Group for Impact Investment",
    "HDI": "Human Development Index",
    "IBAN": "International Bank Account Number",
    "ICSD": "International Central Securities Depository",
    "IICPSD": "Istanbul International Center for Private Sector in Development",
    "IOM": "International Organization for Migration",
    "IoT": "Internet of Things",
    "ISO": "International Organization for Standardization",
    "IT": "Information Technology",
    "iXBRL": "Inline eXtensible Business Reporting Language",
    "JSC": "Joint Stock Company",
    "KhIP": "Kharkiv Innovation Platform",
    "KIC": "Knowledge and Innovation Community",
    "LLC": "Limited Liability Company",
    "M&A": "Mergers and Acquisitions",
    "NAB": "National Advisory Board",
    "NBU": "National Bank of Ukraine",
    "NSSMC": "National Securities and Stock Market Commission",
    "NURE": "Kharkiv National University of Radio Electronics",
    "OPIC": "US Overseas Private Investment Corporation",
    "OSCE": "Organization for Security and Cooperation in Europe",
    "PE": "Private Equity",
    "PRO": "Platform for Effective Regulation",
    "PWD": "Persons with Disabilities",
    "R&D": "Research and Development",
    "SAAS": "Software as a Solution",
    "SE Asia": "East and Southeast Asia",
    "SME": "Small and Medium-sized Enterprise",
    "SMEDO": "SME Development Office",
    "SROI": "Social Return on Investment",
    "SSA": "Sub-Saharan Africa",
    "STEM": "Science, Technology, Engineering, and Mathematics",
    "SUP": "Union of Ukrainian Enterprises",
    "TSP": "Thematic Support Package",
    "UASIF": "Ukrainian Sustainable Fund",
    "UBA": "Ukrainian Business Association",
    "UNDP FSH": "UNDP Finance Sector Hub",
    "UNIDO": "United Nations Industrial Development Organization",
    "UN RPP": "United Nations Recovery and Peacebuilding Programme",
    "USF": "Ukrainian Startup Fund",
    "USVF": "Ukrainian Social Venture Fund",
    "UVCA": "Ukrainian Venture Capital and Private Equity Association",
    "VAT": "Value-Added Tax",
    "VNR": "Voluntary National Review",
    "VR": "Virtual Reality",
    "WNISEF": "Western NIS Enterprise Fund",
    "WNS Europe": "Western, Northern, and Southern Europe",
    "XML": "Extensible Markup Language",
    "RBA": "Regional Bureau Africa"
};